---
- name: Run Nginx container with Docker
  hosts: localhost
  become: true
  connection: local
  tasks:

    - name: Run Nginx container
      community.docker.docker_container:
        name: nginx
        image: nginx:latest
        state: started
        ports:
          - "80:80"

