---
- name: Deploy Website File
  hosts: client
  become: yes
  tasks:
    - name: Copy index.html to client server
      copy:
        src: /var/lib/jenkins/workspace/website-deploy/Ansible-Playbook/index.html
        dest: /root/C-A/website/

