---
- name: Deploy Website File
  hosts: client
  become: yes
  tasks:
    - name: Copy index.html to client server
      copy:
        src: Ansible-Playbook/index.html
        dest: /root/C-A/website/

