---
- name: Deploy Website File
  hosts: all
  become: yes
  tasks:
    - name: Copy index.html to client server
      copy:
        src: Projects/Ansible-Playbook/index.html
        dest: /root/C-A/website/

