---
- name: Install Docker
  hosts: client
  become: true
  tasks:

  - name: Install Docker
    shell: |
     amazon-linux-extras enable docker
     yum clean metadata
     yum install -y docker
#- name: Install Docker 
#  shell: curl -fsSL https://get.docker.com | sh

    - name: Start and enable Docker
      systemd:
        name: docker
        state: started
        enabled: true

