---
- name: Run Nginx container with Docker
  hosts: all
  become: true
  collections:
    - community.docker

  tasks:
    - name: Ensure Nginx container is running
      community.docker.docker_container:
        name: nginx
        image: nginx:latest
        state: started
        restart_policy: always
        published_ports:
          - "80:80"
        volumes:
          - /root/C-A/website:/usr/share/nginx/html:ro
