---
- name: Run Nginx container with Docker
  hosts: localhost
  become: true
  connection: local

  tasks:
    - name: Ensure Nginx container is running
      community.docker.docker_container:
        name: nginx
        image: nginx:latest
        state: started
        restart_policy: always
        published_ports:
          - "80:80"
  volumes:
    - /home/ec2-user/website:/usr/share/nginx/html:ro
